- name: p1 - create disk report in all managed node
  hosts: allservers
  tasks:
    - name: create disk report
      ansible.builtin.shell:
        cmd: "df -h > /tmp/diskreport.txt" 
    - name: Get the content of disk report
      ansible.builtin.command:
        cmd: "cat /tmp/diskreport.txt"
    - name: Use debug module
      ansible.builtin.debug:
        
##ansible-playbook ./3.diskreport.yaml -vv
        
  

#  ansible-playbook ./3.diskreport.yaml --syntax-check
#  ansible-playbook ./3.diskreport.yaml